[pytest]
python_files = test_*.py
python_functions = test_*
python_classes = Test*
testpaths = app/tests
# Add asyncio_mode = auto if using async test functions with pytest-asyncio
# asyncio_mode = auto
